Adding const keyword docs
pyccel/pyccel pull request #1024
Opened 2021-11-05 14:30 UTC by MostafaMamouni

This PR is about adding const keyword docs.

2021-11-22 08:14 UTC, EmilyBourne commented
As per the review process as described [here](https://github.com/pyccel/pyccel/blob/master/developer_docs/review_process.md), please add the `needs_initial_review` label when your PR is ready for review.

2021-11-22 08:17 UTC, EmilyBourne requested changes

2021-11-22 08:17 UTC, EmilyBourne commented on tutorial/const_keyword.md
> +In case if you want to make sure that an argument will not change inside its function, Pyccel provides a `const` keyword which is a qualifier of the data type of the variable and which will be conver
`In case` is not necessary, you can start the sentence with `If`

2021-11-22 08:17 UTC, EmilyBourne commented on tutorial/const_keyword.md
> +In case if you want to make sure that an argument will not change inside its function, Pyccel provides a `const` keyword which is a qualifier of the data type of the variable and which will be conver
I suggest using `the target language` instead of `C/Fortran`. It means one less thing to change if/when we add an additional language

2021-11-22 13:08 UTC, EmilyBourne approved these changes

2021-11-22 17:26 UTC, yguclu requested changes
Thanks @MostafaMamouni! I have a couple of comments.

2021-11-22 17:26 UTC, yguclu commented on tutorial/const_keyword.md
> +If you want to make sure that an argument will not change inside its function, Pyccel provides a `const` keyword which is a qualifier of the data type of the variable and which will be converted to i
I suggest some improvements:
```suggestion
In order to make sure that a function argument is not modified by the function call, Pyccel provides the `const` keyword, which is converted to an equivalent datatype qualifier in the target language. Here is a simple example of its usage:
```

2021-11-22 17:26 UTC, yguclu commented on tutorial/const_keyword.md
> +The fortran equevalent:
Typo: equevalent -> equivalent

2021-11-23 15:17 UTC, yguclu approved these changes

2021-11-23 15:20 UTC, merged