Simplify `(x**2)**0.5` style expressions
pyccel/pyccel pull request #1109
Opened 2022-05-06 11:38 UTC by EmilyBourne

2022-05-09 10:15 UTC, yguclu requested changes
Good job @EmilyBourne! I have a single comment

2022-05-09 10:28 UTC, EmilyBourne commented on pyccel/parser/semantic.py
> +            return PyccelMul(base, base)
Fixed 26c9cf8e

I'm not sure what you mean for `_visit_MathSqrt`. Do you mean that `(x**2)**0.5` should be simplified to `fabs(x)` even if x is a complicated expression?

2022-05-09 10:52 UTC, yguclu commented on pyccel/parser/semantic.py
> +            return PyccelMul(base, base)
Yes, that's what I had in mind... Or do you think that we shouldn't?

2022-05-09 11:03 UTC, EmilyBourne commented on pyccel/parser/semantic.py
> +            return PyccelMul(base, base)
No that sounds right. I just wasn't clear on whether that was what you meant.
Fixed : [c149bf2](https://github.com/pyccel/pyccel/pull/1109/commits/c149bf2d2636ae4f156a8a493a22ce410d545f46)

2022-05-09 14:07 UTC, yguclu approved these changes

2022-05-10 07:02 UTC, yguclu approved these changes

2022-05-10 07:28 UTC, merged