Fix the precision of numpy.abs function
pyccel/pyccel pull request #1177
Opened 2022-08-04 11:37 UTC by EmilyBourne

Fix the precision of `numpy.absolute` function and the internal precision of the real and imaginary parts of a `LiteralComplex`. The latter caused no bugs so far as the precision of the complex was used to interpret the value and no literals with precisions higher than the default precision can be translated. Fixes #1176

2022-08-04 13:18 UTC, aihya approved these changes

2022-09-14 12:08 UTC, yguclu requested changes

2022-09-14 12:08 UTC, yguclu commented on tests/epyccel/recognised_functions/test_numpy_funcs.py
> +
Why do we need to use `isclose` to verify that the absolute value is correct? Assuming that the IEEE 754 standard is respected by all implementations, I would expect all digits to be correct after calling `abs`.

2022-09-14 12:10 UTC, yguclu commented on tests/epyccel/recognised_functions/test_numpy_funcs.py
> +
Sorry. I have just realized that these tests are for complex numbers only. It makes sense to use a tolerance for comparison, then!

2022-09-14 12:12 UTC, yguclu commented on tests/epyccel/recognised_functions/test_numpy_funcs.py
> +
The question remains for testing the functions `absolute_call_r` and `absolute_call_i`. But this not strictly related to this PR.

2022-10-07 09:31 UTC, aihya approved these changes

2022-10-28 08:48 UTC, yguclu approved these changes

2022-10-28 12:24 UTC, merged