Developer documentation for GPU integration with Pyccel
pyccel/pyccel pull request #1290
Opened 2023-01-03 10:21 UTC by bauom

This PR serves as a starting point for discussing the developer documentation for GPU integration with Pyccel. The goal of the documentation is to help developers understand and use Pyccel effectively when building applications that run on GPUs.

We would like to focus on the following topics in the documentation:

`device` and `kernel` decorators
`CUDA` Built-in variables

We welcome feedback and suggestions on these topics, as well as any other ideas you may have for improving the developer documentation on GPU integration with Pyccel. Please share your thoughts on how we can make the documentation more useful and user-friendly for developers working with GPUs.

2023-01-05 11:43 UTC, framdani requested changes

2023-01-05 11:43 UTC, framdani commented on developer_docs/GPU_getting_started.md
> +    The `@kernel` decorator is used to indicate to Pyccel that the function should be compiled as a CUDA kernel, and that it can be launched on a GPU using the appropriate syntax. For example, if we
There seems to be some repetition. Could we rephrase it to something like this, for example ?
```suggestion
By applying the @kernel decorator to a function, Pyccel recognizes it as a CUDA kernel that can be launched on a GPU using the appropriate syntax.
```

2023-01-05 12:25 UTC, bauom commented on developer_docs/GPU_getting_started.md
> +The kernel uses the `cuda.threadIdx(0)`, `cuda.blockIdx(0)`, and `cuda.blockDim(0)` built-in variables to compute the global index of the current thread within the input arrays.
yeah i think this should be added but in a way that doesn't suggest that using `cuda.threadIdx(dim)` where `dim=0` is related to the array size.

2023-01-05 12:26 UTC, bauom commented on developer_docs/GPU_getting_started.md
> +The kernel uses the `cuda.threadIdx(0)`, `cuda.blockIdx(0)`, and `cuda.blockDim(0)` built-in variables to compute the global index of the current thread within the input arrays.
If it is clear that that paragraph only describe the code above your change would make sense but it shouldn't mean that it is a rule on how to use the built-in variables.

2023-01-06 23:33 UTC, EmilyBourne commented
This PR is labelled as developer docs, but it looks like user docs to me. Doesn't this describe how to translate GPU code rather than how to develop GPU related Pyccel code?

2023-01-09 17:23 UTC, bauom commented
> This PR is labelled as developer docs, but it looks like user docs to me. Doesn't this describe how to translate GPU code rather than how to develop GPU related Pyccel code?

I didn't notice as I was writing it, do you think it better to add the specifics of the Pyccel classes in this one or have a user doc that have the stuff written here and just reference it in the developer docs.

2023-01-09 17:30 UTC, EmilyBourne commented
> > This PR is labelled as developer docs, but it looks like user docs to me. Doesn't this describe how to translate GPU code rather than how to develop GPU related Pyccel code?
> 
> I didn't notice as I was writing it, do you think it better to add the specifics of the Pyccel classes in this one or have a user doc that have the stuff written here and just reference it in the developer docs.

Personally, I think this looks good as user docs. I don't see anything aimed at devs so I would just reference it from developer docs

2023-07-25 16:42 UTC, EmilyBourne commented
@bauom Please migrate this PR to the `pyccel/pyccel-cuda` repo. You can transfer your branch to that repo using the following commands:
```
git remote add cuda git@github.com:pyccel/pyccel-cuda.git
git checkout GPU_ddocs
git push -u cuda GPU_ddocs
```

2023-09-05 10:44 UTC, bauom commented
moved to https://github.com/pyccel/pyccel-cuda/pull/22

2023-09-05 10:44 UTC, closed without merging