Fix: Creating Temporary Variable for Functions Passed as Arguments in the function print()
pyccel/pyccel pull request #1404
Opened 2023-05-23 11:15 UTC by sboof911

- I identified a specific problem within the codebase.

- The code changes I made were focused on the `_visit_PythonPrint()` function.

- Within the `_visit_PythonPrint()` function, I introduced a new variable called `tmp_var` to handle cases where an argument in the `args list` is an instance of the `PyccelInternalFunction` class.

- The purpose of the `tmp_var` variable is to store the result of the `_assign_lhs_variable()` function.

- I created a new symbol, `new_symbol`, using the `PyccelSymbol` class.

- To determine the data dictionary, I utilized the `_infer_type()` function, resulting in a `d_var` data dictionary.

- I initialized an empty list, `new_expression`, to store the new expressions related to the allocated variable.

- By invoking the `_assign_lhs_variable()` function with `new_symbol`, `d_var`, and `args[i].value` as inputs, I assigned the data of `args[i].value` to the variable generated by `_assign_lhs_variable()` and stored the output in `tmp_var`.

- I appended the created assignment expression, `creation`, to the `new_expression` list.

- To ensure the new expressions are executed later, I added each expression in the `new_expression` list to the `_additional_exprs list`.

- Finally, I replaced the modified argument in the `args list` with a `FunctionCallArgument` object, using the `tmp_var` variable.

2023-05-23 11:16 UTC, sboof911 commented
/bot show tests

2023-05-23 11:17 UTC, sboof911 commented
/bot run pr_tests

2023-05-23 11:24 UTC, sboof911 commented
@EmilyBourne

2023-05-23 11:59 UTC, sboof911 commented
/bot run pr_tests

2023-05-23 13:05 UTC, EmilyBourne commented
Just to let you know, the PR description serves as a starting point to write the final commit message. It should be a concise summary of the changes you made, and why you made them so that other contributors can quickly understand your changes. You don't need to detail every step in your thought process otherwise some of the bigger PRs would require pages worth of description and no-one would read that :sweat_smile:

2023-05-23 13:22 UTC, sboof911 commented
/bot run pr_tests

2023-05-23 13:32 UTC, sboof911 commented
/bot run pr_tests

2023-05-23 14:28 UTC, EmilyBourne commented
@sboof911 There seems to be a problem with GitHub's actions. While we are waiting for them to come back online, it is important that we keep the bot usage reasonable. Please only use the bot to run tests that you cannot run locally and to mark your PR as ready for review. It is extremely rare to need `/bot run pr_tests`. If you think it is ready, mark it. If you need to check if the tests run you can do this locally. Tests on other OSs only fail in special cases so it is not necessary to test them explicitly. You can wait until marking as "Ready for review" reveals a problem.

I have cancelled your test for now to allow higher priority tests to be run.

2023-05-23 14:52 UTC, sboof911 commented
/bot mark as ready

2023-05-23 15:08 UTC, sboof911 commented
/bot mark as ready

2023-05-23 15:11 UTC, sboof911 commented
/bot mark as ready

2023-05-23 15:12 UTC, EmilyBourne commented
@sboof911 The bot is checking if you have finished your checklist here : https://github.com/pyccel/pyccel/pull/1404#issuecomment-1559088124

It will not let you mark as ready until everything is ticked

2023-05-29 09:58 UTC, sboof911 commented
/bot show tests

2023-05-29 09:59 UTC, sboof911 commented
/bot run coverage

2023-05-29 12:23 UTC, sboof911 commented
/bot run docs

2023-05-29 14:42 UTC, sboof911 commented
/bot run docs

2023-05-29 14:45 UTC, sboof911 commented
/bot coverage

2023-05-29 14:46 UTC, sboof911 commented
/bot run coverage

2023-05-29 15:09 UTC, sboof911 commented
/bot mark as ready

2023-05-31 13:33 UTC, mkaddani approved these changes
Looks good to me!

2023-05-31 15:22 UTC, EmilyBourne requested changes
This looks good. I just have a few comments

2023-05-31 15:22 UTC, EmilyBourne commented on pyccel/parser/semantic.py
> +            if hasattr(arg.value, 'rank') and arg.value.rank and not isinstance(arg.value, (Variable, PythonTuple, IndexedElement)):
Why not use the default argument for `getattr` to make this simpler:
```suggestion
            if getattr(arg.value, 'rank', 0) and not isinstance(arg.value, (Variable, PythonTuple, IndexedElement)):
```

2023-06-02 10:36 UTC, sboof911 commented
/bot run coverage docs pylint

2023-06-02 11:20 UTC, sboof911 commented
/bot mark as ready

2023-06-02 12:13 UTC, EmilyBourne requested changes
This looks much cleaner. But one of my previous comments has not been fixed yet

2023-06-02 13:46 UTC, sboof911 commented on pyccel/parser/semantic.py
> +                args[i] = FunctionCallArgument(tmp_var)
Fixed: d0b34daa5567bf77eb1b2fdeee9bc9648e26a17e

2023-06-02 14:11 UTC, EmilyBourne approved these changes

2023-06-12 13:52 UTC, merged