Raising an error in case of a file named test.py
pyccel/pyccel pull request #1407
Opened 2023-05-25 13:11 UTC by mkaddani

As discussed in #1402 and #1403:
in this pull request i did raise an error in case of a file named ``test.py``.

2023-05-25 13:15 UTC, mkaddani commented
/bot test coverage docs

2023-05-25 13:15 UTC, mkaddani commented
/bot run coverage docs

2023-05-25 15:55 UTC, mkaddani commented
/bot run docs

2023-05-25 16:23 UTC, mkaddani commented
/bot mark as ready

2023-05-25 18:24 UTC, EmilyBourne requested changes

2023-05-26 10:35 UTC, mkaddani commented on tests/internal/test_internal.py
> +    assert str(exc_info.value) == "files called test can cause problems for some compilers and can't be imported from Python. see #issue: 1403"
https://github.com/pyccel/pyccel/blob/566fd73499aa94795d628b8b706566c410a02b96/tests/pyccel/test_pyccel.py#L1001-L1004

2023-05-26 10:37 UTC, mkaddani commented on pyccel/codegen/pipeline.py
> +    if fname == "test.py":
https://github.com/pyccel/pyccel/blob/566fd73499aa94795d628b8b706566c410a02b96/pyccel/codegen/pipeline.py#L112-L113

2023-05-26 14:27 UTC, mkaddani commented
/bot mark as ready

2023-05-26 14:28 UTC, mkaddani commented
/bot mark as ready

2023-05-26 15:16 UTC, EmilyBourne approved these changes
Looks good :+1:

2023-05-30 15:48 UTC, yguclu commented
If the problem is that we cannot pyccelize a file which has the same name of a built-in module, why should we only treat the case of `test.py`? Here is the complete list of all built-in packages in Python 3.11: https://docs.python.org/3/py-modindex.html.

2023-05-30 16:01 UTC, EmilyBourne commented
I agree. `test` is a particular case which comes up a lot. But all the modules in `python_builtin_libs` are potentially problematic. 
https://github.com/pyccel/pyccel/blob/119d5274a1f7c57cfa0ecbb28dc975e1012cc6f2/pyccel/ast/utilities.py#L94-L97

2023-05-31 10:54 UTC, mkaddani commented
/bot mark as ready

2023-05-31 10:55 UTC, EmilyBourne approved these changes

2023-05-31 11:23 UTC, EmilyBourne requested changes

2023-05-31 11:23 UTC, EmilyBourne commented on pyccel/codegen/pipeline.py
> +        raise ValueError(f"File called {os.path.basename(fname)} have same name as python built-in package and can cause problems for some compilers and can't be imported from Python. See #1402")
```suggestion
        raise ValueError(f"File called {os.path.basename(fname)} has the same name as a python built-in package and can't be imported from Python. See #1402")
```
The compiler problem is irrelevant for file names other than "test". There are also a couple of grammar errors here

2023-05-31 13:07 UTC, mkaddani commented
/bot mark as ready

2023-05-31 13:47 UTC, mkaddani commented
since i use random just for testing purposes. should i ignore codacy error:
 ``Standard pseudo-random generators are not suitable for security/cryptographic purposes.``

2023-05-31 15:10 UTC, EmilyBourne commented
> since i use random just for testing purposes. should i ignore codacy error? `Standard pseudo-random generators are not suitable for security/cryptographic purposes.`

Yes I think you can go ahead and do that. You can disable the error for the line as described here : https://pylint.pycqa.org/en/v2.10.2/user_guide/message-control.html#block-disables

2023-06-01 09:49 UTC, mkaddani commented
/bot mark as ready

2023-06-01 10:12 UTC, mkaddani commented
1. its seems that disabling pylint wasn't enough  to disable codacy warning.
2. the docstring error is weird, i didn't add any bind_c module!!
https://github.com/pyccel/pyccel/actions/runs/5142867750/attempts/1#summary-13920707023

2023-06-01 10:12 UTC, EmilyBourne commented on tests/pyccel/test_pyccel.py
> +        libname = str(random.choice(tuple(python_builtin_libs))) + ".py" # pylint: disable=no-member
The error that you are getting is not a no-member error. Please check codacy for the correct keyword

2023-06-01 10:13 UTC, EmilyBourne commented
Please resolve the merge conflicts. Otherwise the errors will probably be quite strange. In particular they tend to point to the wrong line

2023-06-01 10:14 UTC, EmilyBourne commented
> the docstring error is weird, i didn't add any bind_c module!! https://github.com/pyccel/pyccel/actions/runs/5142867750/attempts/1#summary-13920707023

The objects that are reported were deleted in the last PR to be merged. As you haven't updated your branch the CI sees these as new objects on your branch

2023-06-01 10:47 UTC, mkaddani commented
/bot run docs pylint

2023-06-01 11:52 UTC, mkaddani commented
/bot mark as ready

2023-06-01 12:27 UTC, EmilyBourne approved these changes

2023-06-01 14:37 UTC, yguclu commented
@mkaddani Can you please update the title and description of this PR?

2023-06-01 14:50 UTC, mkaddani commented
> @mkaddani Can you please update the title and description of this PR?

done

2023-06-01 17:05 UTC, yguclu requested changes

2023-06-01 17:05 UTC, yguclu commented on pyccel/codegen/pipeline.py
> +    Carry out the main steps required to execute Pyccel
Missing colon:
```suggestion
    Carry out the main steps required to execute Pyccel:
```

2023-06-01 17:05 UTC, yguclu commented on pyccel/codegen/pipeline.py
> +        raise ValueError(f"File called {os.path.basename(fname)} has the same name as a python built-in package and can't be imported from Python. See #1402")
Please capitalize Python

2023-06-02 08:29 UTC, mkaddani commented on CHANGELOG.md
> +-   #1407 : Raise an error if file name matches a Python package module.
fixed: 5a347dacd2b7fb237dada0781ef04f7e9be0ad2a

2023-06-02 08:33 UTC, mkaddani commented on pyccel/codegen/pipeline.py
> +        raise ValueError(f"File called {os.path.basename(fname)} has the same name as a python built-in package and can't be imported from Python. See #1402")
updated: 326459443fc716a50a615b298bd35d97be41b4d6

2023-06-02 08:33 UTC, yguclu commented on CHANGELOG.md
> +-   #1407 : Raise an error if file name matches a Python package module.
Please do not mark a conversation as resolved if you were not the one to open it...

2023-06-02 08:36 UTC, yguclu approved these changes
Thanks! It looks good

2023-06-02 08:39 UTC, mkaddani commented
/bot run docs

2023-06-02 09:15 UTC, merged