adding support python for a simple class
pyccel/pyccel pull request #1446
Opened 2023-07-13 15:47 UTC by sboof911

2023-07-14 10:30 UTC, sboof911 commented
/bot tests

2023-07-14 10:31 UTC, sboof911 commented
/bot show tests

2023-07-14 10:33 UTC, EmilyBourne commented
Don't forget to update your branch before running tests

2023-07-14 10:33 UTC, sboof911 commented
/bot run linux coverage docs pylint lint

2023-07-14 10:34 UTC, EmilyBourne commented
/bot run linux coverage docs pylint lint

2023-07-14 10:34 UTC, EmilyBourne commented
I have cancelled the tests, updated the branch and retriggered the tests. If the branch is not up to date then the comparison between the source and the target branch doesn't work properly. This will be fixed in the new bot

2023-07-14 11:25 UTC, sboof911 commented
/bot mark as ready

2023-07-15 11:06 UTC, mkaddani approved these changes
looks good!

2023-07-15 13:47 UTC, EmilyBourne requested changes
This looks good. Great to finally improve the class support! I just have a couple of comments

2023-07-15 13:47 UTC, EmilyBourne commented on pyccel/codegen/printing/pycode.py
> +        return (f"{str(expr.func_name)}({', '.join([str(arg) for arg in expr.args])})\n")
`join` can take an iterable argument which avoids unnecessary memory allocation

```suggestion
        return (f"{str(expr.func_name)}({', '.join(str(arg) for arg in expr.args)})\n")
```

2023-07-15 13:47 UTC, EmilyBourne commented on pyccel/codegen/printing/pycode.py
> +        methods = ''.join([self._print(method) for method in expr.methods])
See above. `join` can take an iterable argument

2023-07-15 13:47 UTC, EmilyBourne commented on pyccel/codegen/printing/pycode.py
> +        return (f"{str(expr.func_name)}({', '.join([str(arg) for arg in expr.args])})\n")
You should use `self._print` to print objects, not `str()`

2023-07-15 13:47 UTC, EmilyBourne commented on pyccel/codegen/printing/pycode.py
> +        return f"{expr.func.cls_name}({', '.join(str(arg) for arg in expr.arguments)})"
See above. `str` should not be used

2023-07-15 13:47 UTC, EmilyBourne commented on pyccel/codegen/printing/pycode.py
> +        return ''.join([f'del {var}\n' for var in expr.variables])
See above. `join` takes iterable argument

2023-07-17 09:42 UTC, sboof911 commented
/bot mark as ready

2023-07-17 10:32 UTC, EmilyBourne commented
As per the [developer docs](https://github.com/pyccel/pyccel/blob/devel/developer_docs/review_process.md), please don't resolve conversations that you didn't open

> Once your pull request has been reviewed please react to the open conversations. If you disagree you can say this, if not please leave a reference to the commit which fixes the mentioned issue. This makes the review process faster and more streamlined. Please only resolve conversations that you opened. You may think you fixed the problem, but the reviewer may disagree and leaving the discussion open makes it easier for them to verify that they agree with you. If you are reviewing then please close all conversations that you open once the problem is resolved. If you don't this can block the merge.

2023-07-17 10:34 UTC, EmilyBourne commented on pyccel/codegen/printing/pycode.py
> +        return (f"{self._print(expr.func_name)}({', '.join(self._print(arg) for arg in expr.args)})\n")
I think the readability of this line could be improved by introducing intermediate variables. Ie:
```suggestion
        func = self._print(expr.func_name)
        args = ', '.join(self._print(arg) for arg in expr.args)
        return (f"{func}({args})\n")
```

2023-07-17 10:35 UTC, EmilyBourne commented on pyccel/codegen/printing/pycode.py
> +        return f"{expr.func.cls_name}({', '.join(self._print(arg) for arg in expr.arguments)})"
See above, it is not easy to see at a glance what the output string will look like

2023-07-17 10:41 UTC, EmilyBourne commented on pyccel/codegen/printing/pycode.py
> +        return f"{expr.func.cls_name}({', '.join(self._print(arg) for arg in expr.arguments)})"
```suggestion
        args = ', '.join(self._print(arg) for arg in expr.arguments)
        return f"{expr.func.cls_name}({args})"
```

2023-07-17 10:41 UTC, sboof911 commented
/bot mark as ready

2023-07-17 10:43 UTC, EmilyBourne approved these changes
Looks good. Well done

2023-07-19 15:44 UTC, yguclu approved these changes

2023-07-19 15:50 UTC, merged