Add copy() method to ndarray
pyccel/pyccel pull request #1497
Opened 2023-08-15 12:59 UTC by EmilyBourne

Use the existing implementation of `NumpyArray` to add support for `copy`. In the case of the class method the default arguments differ from the `NumpyArray` arguments. This is achieved by adding the `argument_description` parameter to `PyccelFunctionDef`. Fixes #980

2023-08-23 13:51 UTC, yguclu commented
Who should review this pull request into the branch of PR #1256?

2023-08-25 14:21 UTC, yguclu commented
/bot run pr_tests

2023-08-25 14:43 UTC, yguclu requested changes

2023-08-25 14:43 UTC, yguclu commented on docs/numpy-functions.md
> +    -   `array` (`copy`, `subok`, and `like` parameter is not supported).
Typo:
```suggestion
    -   `array` (`copy`, `subok`, and `like` parameters are not supported).
```

2023-08-25 14:43 UTC, yguclu commented on pyccel/ast/core.py
> +        return self._argument_description
I think that `self._argument_description` can be an empty dict `{}`, but never `None`. See `__init__`.

2023-08-25 14:43 UTC, yguclu commented on tests/epyccel/recognised_functions/test_numpy_funcs.py
> +        b = a.copy(order='F')
Typo:
```suggestion
        b = a.copy(order='C')
```

2023-08-25 16:09 UTC, EmilyBourne commented on pyccel/ast/core.py
> +    def __init__(self, name, func_class, *, decorators = {}, argument_description = None):
```suggestion
    def __init__(self, name, func_class, *, decorators = {}, argument_description = {}):
```

2023-08-25 16:09 UTC, EmilyBourne commented on pyccel/ast/core.py
> +        assert argument_description is None or isinstance(argument_description, dict)
```suggestion
        assert isinstance(argument_description, dict)
```

2023-08-25 16:09 UTC, EmilyBourne commented on pyccel/ast/core.py
> +        containing all arguments and their default values. Otherwise return `None`.
```suggestion
        Return a dictionary whose keys are the arguments with default values
        and whose values are the default values for the function described by
        the `PyccelFunctionDef`
```

2023-08-25 16:09 UTC, EmilyBourne commented on pyccel/parser/semantic.py
> +                        kwargs[kw] = val
```suggestion
            # Ignore values passed by position but add any unspecified keywords
            # with the correct default value
            for kw, val in list(argument_description.items())[len(args):]:
                if kw not in kwargs:
                    kwargs[kw] = val
```

2023-08-25 16:14 UTC, EmilyBourne commented
/bot run linux

2023-08-25 16:24 UTC, yguclu requested changes
Looks good, but maybe there is one small improvement to make.

2023-08-25 16:25 UTC, EmilyBourne commented on pyccel/ast/core.py
> +        self._argument_description = argument_description or {}
```suggestion
        self._argument_description = argument_description
```

2023-08-25 16:25 UTC, EmilyBourne commented on pyccel/ast/core.py
> +        self._argument_description = argument_description or {}
Opps. Fixed

2023-08-25 16:27 UTC, yguclu approved these changes

2023-08-25 19:09 UTC, EmilyBourne commented on tests/epyccel/recognised_functions/test_numpy_funcs.py
> +    arr_1d = randint(min_int64, max_int64, size=5)
```suggestion
    arr_1d = randint(min_int, max_int, size=5)
```

2023-08-25 19:09 UTC, EmilyBourne commented
/bot run windows

2023-08-28 09:29 UTC, yguclu approved these changes

2023-08-28 09:31 UTC, merged