Cleanup some datatype handling
pyccel/pyccel pull request #1525
Opened 2023-10-04 10:24 UTC by EmilyBourne

2023-10-04 10:25 UTC, EmilyBourne commented
/bot run coverage docs

2023-10-04 11:14 UTC, EmilyBourne commented
/bot run linux

2023-10-04 12:07 UTC, EmilyBourne commented
/bot run linux

2023-10-04 12:32 UTC, EmilyBourne commented
/bot run docs

2023-10-04 17:24 UTC, EmilyBourne commented
/bot run docs spelling

2023-10-05 17:10 UTC, yguclu requested changes

2023-10-05 17:10 UTC, yguclu commented on pyccel/codegen/printing/ccode.py
> +            The target precision of the of the cast.
Typo: "of the" is repeated.

2023-10-05 17:20 UTC, EmilyBourne commented on pyccel/parser/semantic.py
> +                for entry, d_son in chain(direct_sons, import_sons):
Ah. I forgot to put this in the changelog and description. I noticed that the lapack tests were raising an import warning. It was caused by trying to import functions from the internals via the externals. This change fixes the problem by also checking the imports of the imported module

2023-10-05 17:26 UTC, EmilyBourne commented on pyccel/parser/semantic.py
> +                for entry, d_son in chain(direct_sons, import_sons):
Fixed 81df0a8b

2023-10-05 17:26 UTC, EmilyBourne commented on pyccel/parser/syntax/headers.py
> +        type. These describe the rank and order.
Fixed a0de8337

2023-10-05 17:26 UTC, EmilyBourne commented on pyccel/codegen/printing/ccode.py
> +            The target precision of the of the cast.
Fixed b8954dd3

2023-10-05 19:07 UTC, yguclu approved these changes

2023-10-05 19:17 UTC, merged