Remove dead code
pyccel/pyccel pull request #1584
Opened 2023-10-25 07:46 UTC by EmilyBourne

Pyccel still contains lots of dead code. This makes it harder to work on new developments as apparent dependencies are not always still relevant. This PR removes dead code and unused-imports. The unused elements are:
- `get_attribute` (class attributes are collected from the scope)
- `ForIterator` (mostly superseded by `Iterable` but hasn't been used since 2021 5a7cc8d542e336f3b0a1a390dfddf039172bafa2)
- `inline` (used for untested `With`. These functions don't have to be inline but can be marked with the decorator)
- `subs` (used for `inline`)
- `is_iterable_datatype`
- `is_with_construct_datatype`
- `is_pyccel_datatype`

2023-10-25 07:49 UTC, EmilyBourne commented
/bot checklist

2023-10-25 07:52 UTC, EmilyBourne commented on pyccel/ast/core.py
/bot accept
Known untested code. With sections need class magic methods

2023-10-25 07:52 UTC, EmilyBourne commented
/bot run coverage

2023-10-25 08:07 UTC, EmilyBourne commented
/bot run docs

2023-10-26 12:28 UTC, mkaddani approved these changes
Looks good

2023-10-26 16:56 UTC, yguclu requested changes
Looks good! I have some minor suggestions.

2023-10-26 16:56 UTC, yguclu commented on CHANGELOG.md
> +-   \[INTERNALS\] #1584 : Remove unused functions : `inline`, `subs`, `is_iterable_datatype`, `is_with_construct_datatype`, `is_pyccel_datatype`.
I would specify the modules from which the functions have been removed. Further, I believe the function `get_iterable_ranges` is missing.

2023-10-26 16:56 UTC, yguclu commented on CHANGELOG.md
> +-   \[INTERNALS\] #1584 : Remove unused class `ForIterator`.
Same comment: this was removed from `pyccel.ast.core`.

2023-10-26 16:56 UTC, yguclu commented on CHANGELOG.md
> +-   \[INTERNALS\] #1584 : Remove unused method `get_attribute`.
Same comment as above. For clarity I would also mention the class: `ClassDef.get_attribute`.

2023-10-27 05:56 UTC, yguclu commented on CHANGELOG.md
> +-   \[INTERNALS\] #1584 : Remove unused method `get_attribute`.
1c808dd

2023-10-27 05:57 UTC, yguclu approved these changes

2023-10-27 06:35 UTC, EmilyBourne commented
/bot run pr_tests

2023-10-27 07:13 UTC, merged