Added Test cases to pyccel/tests/epyccel/modules/tuples.py
pyccel/pyccel pull request #1589
Opened 2023-10-28 08:11 UTC by imperial-chief

2023-10-28 12:46 UTC, EmilyBourne commented
/bot run docs spelling pylint pyccel_lint coverage

2023-10-28 12:58 UTC, EmilyBourne commented
/bot run docs spelling pylint pyccel_lint coverage

2023-10-28 13:18 UTC, EmilyBourne commented
/bot run docs spelling pylint pyccel_lint coverage

2023-10-28 13:27 UTC, EmilyBourne commented
/bot run docs

2023-10-28 13:46 UTC, EmilyBourne commented
/bot run coverage

2023-10-30 13:39 UTC, EmilyBourne commented
/bot run coverage

2023-10-30 14:03 UTC, EmilyBourne commented
/bot run coverage

2023-10-31 06:28 UTC, imperial-chief commented
/bot checklist

2023-10-31 08:00 UTC, EmilyBourne commented on CHANGELOG.md
> +-   #1571 : Add support for the function `tuple`.
There is already an "Added" section above. Please can you move the bullet point to the existing section

2023-10-31 11:02 UTC, imperial-chief commented
/bot run pr_tests

2023-11-01 07:47 UTC, EmilyBourne approved these changes

2023-11-02 08:57 UTC, yguclu requested changes
Looks good to me!

2023-11-02 08:57 UTC, yguclu commented on CHANGELOG.md
> +
Please remove useless empty line.

2023-11-02 10:41 UTC, yguclu commented on CHANGELOG.md
> +
Done in f0941c2.

2023-11-02 10:41 UTC, yguclu approved these changes

2023-11-02 13:32 UTC, yguclu commented
\bot run pr_tests

2023-11-02 13:36 UTC, EmilyBourne commented
/bot run pr_tests

2023-11-02 15:35 UTC, EmilyBourne commented
/bot run pr_tests

2023-11-02 16:04 UTC, merged