Class simplifications
pyccel/pyccel pull request #1676
Opened 2024-01-17 10:08 UTC by EmilyBourne

2024-01-17 10:10 UTC, EmilyBourne commented
/bot checklist

2024-01-17 10:47 UTC, EmilyBourne commented
/bot run coverage

2024-01-17 11:08 UTC, EmilyBourne commented on pyccel/codegen/printing/fcode.py
> +            name = f'{self.prefix_module}_{name}'
/bot accept
See #1677

2024-01-17 11:10 UTC, EmilyBourne commented on pyccel/codegen/printing/fcode.py
> +                        suggested_name = _default_methods[i_name]
/bot accept
Currently only `create` and `free` are found in `_default_methods`. These do not appear in interfaces. However this code should be kept to support magic methods in the future

2024-01-17 11:58 UTC, EmilyBourne commented
/bot run pylint docs

2024-01-17 12:03 UTC, EmilyBourne commented
/bot run pylint docs

2024-01-24 12:07 UTC, yguclu requested changes
Looks good to me!

2024-01-24 12:12 UTC, EmilyBourne commented on pyccel/ast/core.py
> +        self._bound_argument = bound
Fixed bc40a292b

2024-01-24 12:14 UTC, yguclu approved these changes

2024-01-24 12:15 UTC, yguclu approved these changes

2024-01-24 12:46 UTC, merged