Get actual Homebrew directory from environment variable
pyccel/pyccel pull request #1713
Opened 2024-02-04 22:00 UTC by yguclu

This fixes #1712.

2024-02-04 22:03 UTC, yguclu commented
/bot checklist

2024-02-04 22:05 UTC, yguclu commented
Most points in the bot checklist do not really apply to this PR. I have checked that the OpenMP tests now work on Apple Silicon chips (on `devel` they fail because of the wrong path).

2024-02-04 22:06 UTC, yguclu commented
/bot commands

2024-02-04 22:07 UTC, yguclu commented
/bot show tests

2024-02-04 22:07 UTC, yguclu commented
/bot run macosx

2024-02-04 22:54 UTC, yguclu commented
/bot run macosx

2024-02-04 23:09 UTC, yguclu commented
/bot run pr_tests

2024-02-04 23:26 UTC, yguclu commented on pyccel/compilers/default_compilers.py
> +    p = subprocess.run([shutil.which('brew'), '--prefix'], check=True, capture_output=True)
/bot accept This code is used on macOS.

2024-02-05 08:20 UTC, EmilyBourne requested changes
I think this is worth mentioning in the CHANGELOG

2024-02-05 12:41 UTC, yguclu commented
> I think this is worth mentioning in the CHANGELOG

Done in 33ea297. Is that sufficient for you?

2024-02-05 12:49 UTC, EmilyBourne commented
> > I think this is worth mentioning in the CHANGELOG
> 
> Done in [33ea297](https://github.com/pyccel/pyccel/commit/33ea297fce85cdc53b671f2b5abd25180be93505). Is that sufficient for you?

It is ok but I think it would be better to reference the issue. If this is a problem with OpenMP then I think something like:
```
-   #1712 : Fix library path and OpenMP support for recent Apple chips by getting Homebrew directory with `brew --prefix`.
```

But this may be a little long. I imagine if someone is looking for whether/when OpenMP is fixed they would search OpenMP not Homebrew. The cause of this bug is not necessarily obvious to the user in my opinion so I am not sure that they would be able to connect it to this message.

2024-02-05 14:28 UTC, EmilyBourne approved these changes

2024-02-05 17:27 UTC, merged