List support/remove method
pyccel/pyccel pull request #1790
Opened 2024-03-14 10:30 UTC by Farouk-Echaref

2024-03-14 10:57 UTC, Farouk-Echaref commented
/bot checklist

2024-03-14 14:39 UTC, Farouk-Echaref commented
/bot run pr_tests

2024-03-18 12:47 UTC, Farouk-Echaref commented
/bot run pr_tests

2024-03-18 15:08 UTC, Farouk-Echaref commented
/bot mark as ready

2024-03-18 16:15 UTC, mustapha-belbiad approved these changes
Looks good.

2024-03-18 16:21 UTC, EmilyBourne approved these changes
Looks good to me too

2024-03-18 19:01 UTC, EmilyBourne commented
/bot run pr_tests

2024-03-18 22:15 UTC, yguclu requested changes
Looks good!

2024-03-18 22:15 UTC, yguclu commented on pyccel/ast/builtin_methods/list_methods.py
> +    Represents a call to the .remove() method which removes the first occurence
Typo: occurence -> occurrence

2024-03-19 12:26 UTC, Farouk-Echaref commented
/bot mark as ready

2024-03-19 17:11 UTC, yguclu approved these changes

2024-03-19 18:12 UTC, merged