Clean up unnecessary arguments in the codegen stage
pyccel/pyccel pull request #1791
Opened 2024-03-17 10:20 UTC by EmilyBourne

2024-03-17 10:25 UTC, EmilyBourne commented
/bot checklist

2024-03-17 10:41 UTC, EmilyBourne commented
/bot run docs linux pylint

2024-03-17 10:46 UTC, EmilyBourne commented
/bot run docs

2024-03-18 12:05 UTC, yguclu requested changes
Looks good to me!

I have just two minor comments.

2024-03-18 12:09 UTC, Farouk-Echaref commented on pyccel/codegen/printing/ccode.py
> -def ccode(expr, filename, assign_to=None, **settings):
what were the roles of these functions before? (ccode(), fcode(), pycode())

2024-03-18 13:44 UTC, EmilyBourne commented on pyccel/codegen/codegen.py
> +        The Pyccel Semantic parser node.
Fixed a2954f495

2024-03-18 13:44 UTC, EmilyBourne commented on CHANGELOG.md
> +-   \[INTERNALS\] Removed unused `Xcode` functions from printers.
Fixed 1e5f5507e

2024-03-18 13:48 UTC, Farouk-Echaref commented on pyccel/codegen/printing/ccode.py
> -def ccode(expr, filename, assign_to=None, **settings):
Clear enough, thanks for the clarification!

2024-03-18 14:21 UTC, yguclu approved these changes

2024-03-18 16:04 UTC, merged