Simplify `epyccel` import
pyccel/pyccel pull request #1855
Opened 2024-04-29 15:33 UTC by EmilyBourne

Move `epyccel.py` to `pyccel/commands/` folder. This allows a shortcut to be introduced for the import of the most commonly used `epyccel` function. It is now possible to do `from pyccel import epyccel`. Fixes #1836.

2024-04-29 15:34 UTC, EmilyBourne commented
/bot checklist

2024-04-29 15:59 UTC, EmilyBourne commented
/bot run docs spelling

2024-04-29 16:25 UTC, EmilyBourne commented
/bot run docs

2024-04-29 16:55 UTC, EmilyBourne commented
/bot run pr_tests

2024-04-29 16:55 UTC, EmilyBourne commented
/bot run pr_tests

2024-04-29 17:01 UTC, EmilyBourne commented
Blocked by #1856

2024-05-02 13:21 UTC, yguclu requested changes
Nice!

2024-05-02 13:21 UTC, yguclu commented on tests/epyccel/test_loops.py
>  from modules        import loops
Alignment is broken, so we can just remove the blank spaces
```suggestion
from pyccel import epyccel
from modules import loops
```

2024-05-02 13:21 UTC, yguclu commented on tests/epyccel/test_mpi_point_to_point.py
>  from modules        import mpi_point_to_point as pmod
```suggestion
from pyccel import epyccel
from modules import mpi_point_to_point as pmod
```

2024-05-02 13:28 UTC, EmilyBourne commented
/bot run pylint

2024-05-02 13:30 UTC, yguclu approved these changes

2024-05-02 13:30 UTC, yguclu commented on tests/epyccel/test_loops.py
> +from modules import loops
Python linting:
```suggestion
from modules import loops

from pyccel import epyccel
```

2024-05-02 13:30 UTC, yguclu commented on tests/epyccel/test_mpi_point_to_point.py
> +from modules import mpi_point_to_point as pmod
Python linting:
```suggestion
from modules import mpi_point_to_point as pmod

from pyccel import epyccel
```

2024-05-02 14:39 UTC, merged