WIP: Replace ndarrays with STC's cspan
pyccel/pyccel pull request #1969
Opened 2024-08-28 06:32 UTC by EmilyBourne

2024-08-28 06:33 UTC, EmilyBourne commented
Blocked by #1963

2024-08-28 06:34 UTC, EmilyBourne commented
/bot checklist

2024-10-10 14:24 UTC, EmilyBourne commented on pyccel/codegen/printing/ccode.py
> +        return sorted_imports
@jalalium

2024-11-05 12:13 UTC, EmilyBourne commented
/bot run macosx

2024-11-06 16:22 UTC, EmilyBourne commented
/bot run pylint pyccel_lint docs

2024-11-06 16:33 UTC, EmilyBourne commented
/bot run pylint

2024-11-06 16:41 UTC, EmilyBourne commented
/bot run linux

2024-11-07 16:59 UTC, EmilyBourne commented
/bot try 3.11 linux

2024-11-08 13:55 UTC, EmilyBourne commented
/bot try 3.11 linux

2024-11-08 14:45 UTC, EmilyBourne commented
/bot try 3.11 linux

2024-11-08 15:44 UTC, EmilyBourne commented
/bot try 3.11 linux

2024-11-08 16:42 UTC, EmilyBourne commented
/bot try 3.11 linux

2024-12-24 13:53 UTC, EmilyBourne commented
/bot run docs spelling pylint

2024-12-24 14:03 UTC, EmilyBourne commented
/bot run docs coverage

2024-12-24 14:11 UTC, EmilyBourne commented
/bot run docs

2024-12-24 14:26 UTC, EmilyBourne commented on pyccel/ast/low_level_tools.py
> +
/bot accept
Pickling is tested during installation

2025-01-15 16:57 UTC, jalalium requested changes
halfway done with the review

2025-01-15 16:57 UTC, jalalium commented on pyccel/codegen/printing/ccode.py
> +                 'CSpan_extensions']}
Could you please add this import to the dicts below?

2025-01-16 08:16 UTC, EmilyBourne commented on pyccel/codegen/printing/ccode.py
> +                 'CSpan_extensions']}
I'm not sure that this would be helpful.
`cspan` works a little differently to other STC modules. For example it only needs importing once for all types. The different types are then initialised with the macro `using_cspan`.
(I was not respecting this rule but have updated in [265ad9e](https://github.com/pyccel/pyccel/pull/1969/commits/265ad9e2aa30fc3ec24cb69460aadf79d331448e) to remove the unnecessary extra imports).
This means that the include for `cspan` is handled with its own logic. As a result I don't think there is any advantage to be had by adding `CSpan_extensions` to the dictionary `stc_extension_mapping`.

I can ensure that it is always included when `cspan` is included but this is less critical as it is for other extensions. As the file only contains macros it has its own header guard which means there is no risk that the lack of an import in one file can affect a different file. Further if I remove the explicit import I am not sure how to ensure that the folder `STC_extensions` is compiled and included.

If we decide that `STC_extensions` should be included systematically and implicitly then I think this PR should wait until after #2156 as I suspect that this will encounter a similar problem

2025-01-22 12:21 UTC, jalalium requested changes
`CNameClashChecker` also needs updating.
New keywords need to be added such as `c_ROWMAJOR`

2025-01-22 12:32 UTC, EmilyBourne commented on pyccel/codegen/printing/ccode.py
> +
Fixed [cb9b2cd](https://github.com/pyccel/pyccel/pull/1969/commits/cb9b2cdc3028b9ebc89a6c155baba76f7fb380f6)

2025-01-22 12:35 UTC, EmilyBourne commented on pyccel/codegen/printing/ccode.py
> +            order = 'c_COLMAJOR' if variable.order == 'F' else 'c_ROWMAJOR'
> This should be handled right?

I'm not sure what you mean?

The order should be `None` here as order is a concept which doesn't really mean anything for arrays with rank<2. Internally Pyccel only saves orders which represent something. So for a 1D array we save `None` even if something was specified. NumPy saves C and Fortran
![image](https://github.com/user-attachments/assets/54c4a2af-4074-4dea-8da8-4636d5bf7479)
For an array with order `None`, if an order needs to be specified, I use the default order of the language. So here it should be `c_ROWMAJOR` which is indeed what is implemented

2025-01-22 12:52 UTC, EmilyBourne commented
> `CNameClashChecker` also needs updating. New keywords need to be added such as `c_ROWMAJOR`

Fixed [9ec9d83](https://github.com/pyccel/pyccel/pull/1969/commits/9ec9d83505a2647447089049ed33b0caf977a5c1)

2025-01-22 12:59 UTC, EmilyBourne commented
/bot run pr_tests

2025-01-22 13:30 UTC, jalalium commented on pyccel/codegen/printing/ccode.py
> +            order = 'c_COLMAJOR' if variable.order == 'F' else 'c_ROWMAJOR'
Sorry bad example. This is better:
```Python
    x = np.array([[1,2,3],[12,3,4]], order='F')
```
```C
    x = (array_int64_2d)cspan_md_layout(c_COLMAJOR, x_ptr, INT64_C(2), INT64_C(3));
```

2025-01-22 13:32 UTC, EmilyBourne commented on pyccel/codegen/printing/ccode.py
> +            order = 'c_COLMAJOR' if variable.order == 'F' else 'c_ROWMAJOR'
I still don't see the problem :sweat_smile: what do you expect to be printed here instead?

2025-01-22 14:16 UTC, jalalium commented on pyccel/codegen/printing/ccode.py
> +            order = 'c_COLMAJOR' if variable.order == 'F' else 'c_ROWMAJOR'
My bad, My bad 😅😅😅😅, I was expecting `f_ROWMAJOR` 😅😅😅😅. didn't even read `row/col`.

2025-01-22 14:17 UTC, jalalium approved these changes
Amazing Job!

2025-01-22 14:19 UTC, merged