[DICT] Add Python support for clear
pyccel/pyccel pull request #2029
Opened 2024-10-29 18:18 UTC by leonardopaloschi

Files dict_methods.py, class_defs.py, test_epyccel_dicts.py and pycode.py were changed. Reference to issue #1880.

2024-10-29 18:20 UTC, leonardopaloschi commented
/bot checklist

2024-10-29 18:45 UTC, EmilyBourne commented on tests/epyccel/test_epyccel_dicts.py
> +        return a
You will need to use `len` to test in order to be able to test other languages (C/Fortran) as returning a dictionary is not yet supported for these languages
```suggestion
        a.clear()
        return len(a)
```

2024-10-29 18:47 UTC, EmilyBourne commented on tests/epyccel/test_epyccel_dicts.py
> +    assert len(pyccel_result) == 0
You don't need to use `len` outside the function that is translated. You are already returning the dictionary (this is ok as you are only translating to Python) so you can simply do:
```suggestion
    assert python_result == pyccel_result
```

2024-10-29 18:48 UTC, EmilyBourne commented on pyccel/codegen/printing/pycode.py
> +        return f"{dict_obj}.clear()\n"
Are you sure that this is needed? I would expect `_print_DictMethod` to be sufficient

2024-10-29 18:50 UTC, EmilyBourne commented
/bot trust user leonardopaloschi

2024-10-29 19:02 UTC, EmilyBourne commented
Please make sure to [link your pull request to the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue) so it will automatically be closed when the PR is merged.

2024-11-04 17:42 UTC, leonardopaloschi commented
Hi @EmilyBourne,

I’ve made all the changes you requested. I deleted the print method, updated the assert, and changed the _class_type. The only thing I’m unsure about is the type; I committed it with InhomogeneousTupleType(), but I’m not sure if it should be VoidType() in that context.

Let me know what you think! If everything looks good, please let me know what else I need to do.

Thanks!

2024-11-04 19:50 UTC, EmilyBourne commented
I think `VoidType` is probably right. The type describes the type of the result of the function. So the type of `a` in:
```python
def f(b : dict[int, float]):
    a = b.clear()
```
`VoidType()` is used if the function doesn't return anything. `InhomogeneousTupleType` would be the type of `()`.

Please check with the bot for the next steps. I will leave a complete review when the bot requests it

2024-11-04 20:37 UTC, leonardopaloschi commented
/bot mark as ready

2024-11-04 20:46 UTC, leonardopaloschi commented
/bot show tests

2024-11-04 20:48 UTC, leonardopaloschi commented
/bot run pr_tests

2024-11-04 21:49 UTC, leonardopaloschi commented
/bot mark as ready

2024-11-04 21:54 UTC, leonardopaloschi commented
Hi, Emily.
It seems that all the tests passed except for the documentation one. However, the error reported is related to the docstring of a part of the code that apparently has no connection to what I did, so I would like to know what I can do to have the PR reviewed. Thank you in advance.

2024-11-05 06:14 UTC, EmilyBourne commented
@leonardopaloschi the documentation test compares with the devel branch. As your branch is not up to date with devel it sees docs that have been added on devel as things that have been removed on your branch. Please merge devel into your branch and fix the conflicts. This should fix the problem

2024-11-05 09:02 UTC, EmilyBourne requested changes
This looks good. I just have a couple of minor comments.
I see that you have ticked the items corresponding to the AUTHORS and the CHANGELOG in your checklist but I don't see these changes. Please can you fix this

2024-11-05 09:02 UTC, EmilyBourne commented on pyccel/ast/builtin_methods/dict_methods.py
> +class DictClear(DictMethod) :
As per PEP: https://peps.python.org/pep-0008/#blank-lines
> Surround top-level function and class definitions with two blank lines.

```suggestion
        return self._args[1]

#==============================================================================
class DictClear(DictMethod) :
```

2024-11-05 20:13 UTC, leonardopaloschi commented
/bot mark as ready

2024-11-05 20:14 UTC, leonardopaloschi commented
/bot mark as ready

2024-11-05 20:48 UTC, EmilyBourne approved these changes
This looks good. Thank you for these changes

2024-11-05 21:02 UTC, EmilyBourne commented
/bot run pr_tests

2024-11-05 21:12 UTC, EmilyBourne commented on tests/epyccel/test_epyccel_dicts.py
> +    assert python_result == pyccel_result
```suggestion
    assert python_result == pyccel_result

```

2024-11-06 07:34 UTC, EmilyBourne commented on pyccel/ast/class_defs.py
> +from pyccel.ast.builtin_methods.dict_methods  import DictPop, DictPopitem, DictGet, DictClear,
```suggestion
from pyccel.ast.builtin_methods.dict_methods  import (DictPop, DictPopitem, DictGet, DictClear,
```

2024-11-06 07:34 UTC, EmilyBourne commented on pyccel/ast/class_defs.py
> +from pyccel.ast.builtin_methods.dict_methods  import (DictPop, DictPopitem, DictGet, DictClear,
```suggestion
from pyccel.ast.builtin_methods.dict_methods import (DictPop, DictPopitem, DictGet, DictClear,
```

2024-11-06 07:58 UTC, EmilyBourne commented
/bot run pr_tests

2024-11-06 08:08 UTC, merged