Add support for `dict.items`
pyccel/pyccel pull request #2073
Opened 2024-11-20 12:45 UTC by EmilyBourne

2024-11-20 12:47 UTC, EmilyBourne commented
/bot checklist

2024-11-20 12:52 UTC, EmilyBourne commented
/bot run macosx

2024-11-22 16:06 UTC, EmilyBourne commented
/bot run docs pylint pyccel_lint

2024-11-22 16:13 UTC, EmilyBourne commented
/bot run docs pylint pyccel_lint coverage

2024-11-23 11:45 UTC, EmilyBourne commented
/bot run docs pylint pyccel_lint coverage

2024-11-23 11:55 UTC, EmilyBourne commented
/bot run docs pylint pyccel_lint coverage

2024-11-23 12:44 UTC, EmilyBourne commented
/bot run coverage

2024-11-23 13:58 UTC, EmilyBourne commented
/bot run coverage

2024-11-23 16:26 UTC, EmilyBourne commented
/bot run coverage

2024-11-26 14:46 UTC, jalalium requested changes
Awesome Job, this refactoring is great!

2024-11-26 14:46 UTC, jalalium commented on pyccel/ast/internals.py
> +        (e.g. var[idx] for the iterable enumerate(var) with targets idx, var_idx).
I think this example can be clearer

2024-11-26 15:10 UTC, EmilyBourne commented on pyccel/ast/internals.py
> +        (e.g. var[idx] for the iterable enumerate(var) with targets idx, var_idx).
Better?
e0df50a20

2024-11-27 09:48 UTC, jalalium commented on pyccel/ast/internals.py
> +        (e.g. var[idx] for the iterable enumerate(var) with targets idx, var_idx).
Awesome!

2024-11-27 09:49 UTC, jalalium approved these changes
Excellent job!

2024-11-27 09:52 UTC, merged