Ignore __all__ statements
pyccel/pyccel pull request #2100
Opened 2024-12-05 15:58 UTC by EmilyBourne

2024-12-05 17:08 UTC, EmilyBourne commented
/bot checklist

2024-12-06 15:03 UTC, EmilyBourne commented
/bot run pyccel_lint docs

2024-12-06 15:08 UTC, EmilyBourne commented
/bot run docs

2024-12-09 09:46 UTC, jalalium requested changes
Maybe we can add a doc section about supported magic attributes

2024-12-09 09:46 UTC, jalalium commented on pyccel/parser/semantic.py
I think it would be best to remove the following warning in this case:
```bash
 |warning [semantic]: boo.py| Nested lists are not yet fully supported. Using containers in lists may lead to bugs such as memory leaks (list[str])
```

2024-12-09 20:56 UTC, EmilyBourne commented on pyccel/parser/semantic.py
Fixed a24811ade, but I am hoping to remove this warning before v2.0 (it should go with #1959

2024-12-23 08:55 UTC, jalalium approved these changes
Well done!

2024-12-23 09:03 UTC, merged