Fix RecursionError when calling a recursive class method bug
pyccel/pyccel pull request #2107
Opened 2024-12-14 10:42 UTC by EmilyBourne

2025-01-15 16:52 UTC, EmilyBourne commented
/bot checklist

2025-01-28 15:26 UTC, EmilyBourne commented
/bot run pylint spelling coverage

2025-02-18 14:01 UTC, EmilyBourne commented
@jalalium just to give you an update. I am having trouble with indexed elements. You mentioned:

> In addition, support for indexed elements seems fine in LHS and RHS but fails if in both ie:
```python
if __name__ == '__main__':
    a = [2,5]
    a[0],a[1] = a[1],a[0]
    print(a)
```

The method implemented for Variables cannot be extended to IndexedElements as an `IndexedElement` is not a singleton.

I am also worried about assumptions that may be implicit. E.g. in:
```
a[i], a[j] = a[j], a[i]
```
could/should I assume that `i != j`?

2025-02-24 09:40 UTC, EmilyBourne commented
/bot run pyccel_lint pylint spelling docs

2025-02-24 14:32 UTC, yguclu reviewed
Can the proposed code handle this?
```python
a : float
b : int
c : float
d : int
...
a, b, c, d = c, d, a, b
```

2025-02-24 14:36 UTC, EmilyBourne commented
> Can the proposed code handle this?
> 
> ```python
> a : float
> b : int
> c : float
> d : int
> ...
> a, b, c, d = c, d, a, b
> ```

Yes, this generates:
```fortran
  Dummy_0000 = a
  a = c
  Dummy_0001 = b
  b = d
  c = Dummy_0000
  d = Dummy_0001
```

2025-02-25 08:26 UTC, yguclu commented
> > Can the proposed code handle this?
> > ```python
> > a : float
> > b : int
> > c : float
> > d : int
> > ...
> > a, b, c, d = c, d, a, b
> > ```
> 
> Yes, this generates:
> 
> ```fortran
>   Dummy_0000 = a
>   a = c
>   Dummy_0001 = b
>   b = d
>   c = Dummy_0000
>   d = Dummy_0001
> ```

That's great, but I could not find a similar example among the unit tests.

2025-02-25 08:27 UTC, EmilyBourne commented
> > > Can the proposed code handle this?
> > > ```python
> > > a : float
> > > b : int
> > > c : float
> > > d : int
> > > ...
> > > a, b, c, d = c, d, a, b
> > > ```
> > 
> > 
> > Yes, this generates:
> > ```fortran
> >   Dummy_0000 = a
> >   a = c
> >   Dummy_0001 = b
> >   b = d
> >   c = Dummy_0000
> >   d = Dummy_0001
> > ```
> 
> That's great, but I could not find a similar example among the unit tests.

`test_swap_basic_3` ?

2025-02-25 09:14 UTC, yguclu commented
> `test_swap_basic_3`

I do not think so. The variables `a, b, c` are all of the same `int` type.

2025-02-25 09:58 UTC, EmilyBourne commented
> > `test_swap_basic_3`
> 
> I do not think so. The variables `a, b, c` are all of the same `int` type.

Test added : [c89af55](https://github.com/pyccel/pyccel/pull/2107/commits/c89af5503d69e6bcd5be384f73967ccf6448ec86)

2025-02-25 10:22 UTC, yguclu requested changes
Looks good, but should you not check that the correct error is raised when the multiple assignment cannot be handled as a swap?

2025-02-25 10:35 UTC, EmilyBourne commented
> Looks good, but should you not check that the correct error is raised when the multiple assignment cannot be handled as a swap?

That would be nice but I don't have any examples. I wrote that as a fallback so the user has a clear error message if my assumptions about what I have parsed turn out to be wrong. I'm not sure what might trigger this. If I found one I would probably try to make it work rather than using it as an error test

2025-02-25 11:06 UTC, yguclu commented
> > Looks good, but should you not check that the correct error is raised when the multiple assignment cannot be handled as a swap?
> 
> That would be nice but I don't have any examples. I wrote that as a fallback so the user has a clear error message if my assumptions about what I have parsed turn out to be wrong. I'm not sure what might trigger this. If I found one I would probably try to make it work rather than using it as an error test

All right! I have no further objections then

2025-02-25 11:06 UTC, yguclu approved these changes

2025-02-25 14:45 UTC, yguclu submitted a review, later dismissed
Excellent!

2025-02-26 11:50 UTC, jalalium approved these changes
Excellent!

2025-02-26 11:54 UTC, EmilyBourne commented
/bot run docs pylint

2025-02-26 15:44 UTC, yguclu commented on tests/epyccel/test_arrays_multiple_assignments.py
> +    assert warning_info.symbol in ('x', "'x'")
The symbol is a string which could be quoted?

2025-02-26 15:56 UTC, EmilyBourne commented on tests/epyccel/test_arrays_multiple_assignments.py
> +    assert warning_info.symbol in ('x', "'x'")
When tests are run in developer-mode we use `repr` instead of `str` to get more information about the objects causing the errors. `str(PyccelSymbol('x'))` gives `'x'` but `repr(PyccelSymbol('x'))` gives `"'x'"`

2025-02-26 16:36 UTC, yguclu approved these changes
Looks good to me

2025-02-26 16:54 UTC, merged