Fix multiple calls to `_build_gFTL_extension_module`
pyccel/pyccel pull request #2114
Opened 2024-12-16 11:49 UTC by EmilyBourne

Fix error when there are multiple calls to `_build_gFTL_extension_module`. Fixes #2103 .
This error is due to illogical usage of `matching_expr_type`. The error was introduced since the last version so this is not added to the CHANGELOG.

2024-12-16 11:49 UTC, EmilyBourne commented
/bot checklist

2024-12-23 09:57 UTC, jalalium requested changes

2024-12-23 09:57 UTC, jalalium commented on pyccel/codegen/printing/fcode.py
> +            print(matching_expr_extensions, type(matching_expr_extensions))
forgotten debug print?

2024-12-23 10:32 UTC, EmilyBourne commented on pyccel/codegen/printing/fcode.py
> +            print(matching_expr_extensions, type(matching_expr_extensions))
```suggestion
```

2025-01-07 11:43 UTC, jalalium reviewed
```python

def update_multiple():
    a = {1, 2, 3}
    a.update({4, 5})
    return len(a)

def set_union():
    a = {1,2,3,4,5}
    b = {4,5,6}
    d = {1.2}
    c = a.union(b)
    return len(c)

if __name__ == '__main__':
    print(update_multiple())
    print(set_union())
```
In this example, we get the following program:
```Fortran
program prog_prog_boo

  use boo
  use Set_integer8_mod
  use Set_integer8_extensions_mod
  use Set_real8_mod

  use, intrinsic :: ISO_C_Binding, only : f64 => C_DOUBLE , i64 => &
        C_INT64_T
  use, intrinsic :: ISO_FORTRAN_ENV, only : stdout => output_unit

  implicit none

  write(stdout, '(I0)', advance="yes") update_multiple()
  write(stdout, '(I0)', advance="yes") set_union()

end program prog_prog_boo
```
Can we avoid printing
```Fortran
  use Set_integer8_mod
  use Set_integer8_extensions_mod
  use Set_real8_mod
```
since we already use them in `boo`?

2025-01-07 12:07 UTC, EmilyBourne commented
> ```python
> def update_multiple():
>     a = {1, 2, 3}
>     a.update({4, 5})
>     return len(a)
> 
> def set_union():
>     a = {1,2,3,4,5}
>     b = {4,5,6}
>     d = {1.2}
>     c = a.union(b)
>     return len(c)
> 
> if __name__ == '__main__':
>     print(update_multiple())
>     print(set_union())
> ```
> 
> In this example, we get the following program:
> 
> ```fortran
> program prog_prog_boo
> 
>   use boo
>   use Set_integer8_mod
>   use Set_integer8_extensions_mod
>   use Set_real8_mod
> 
>   use, intrinsic :: ISO_C_Binding, only : f64 => C_DOUBLE , i64 => &
>         C_INT64_T
>   use, intrinsic :: ISO_FORTRAN_ENV, only : stdout => output_unit
> 
>   implicit none
> 
>   write(stdout, '(I0)', advance="yes") update_multiple()
>   write(stdout, '(I0)', advance="yes") set_union()
> 
> end program prog_prog_boo
> ```
> 
> Can we avoid printing
> 
> ```fortran
>   use Set_integer8_mod
>   use Set_integer8_extensions_mod
>   use Set_real8_mod
> ```
> 
> since we already use them in `boo`?

I'm not sure that this is really related to this PR.

I agree that these imports are superfluous but they are a little tricky to avoid. We need to print all imports that are pertinent to the scope. If we do `use boo` we only get the public methods from `boo` so we shouldn't get access to anything imported inside the `boo` module. This is why all pertinent imports included by `boo` need repeating in the program. If the program scope was completely separate from the module scope then the number of imports used here could be reduced but in Python the program scope is a child of the module scope so the program should have access to all the objects imported in the module.

2025-01-08 15:32 UTC, jalalium commented
> > ```python
> > def update_multiple():
> >     a = {1, 2, 3}
> >     a.update({4, 5})
> >     return len(a)
> > 
> > def set_union():
> >     a = {1,2,3,4,5}
> >     b = {4,5,6}
> >     d = {1.2}
> >     c = a.union(b)
> >     return len(c)
> > 
> > if __name__ == '__main__':
> >     print(update_multiple())
> >     print(set_union())
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In this example, we get the following program:
> > ```fortran
> > program prog_prog_boo
> > 
> >   use boo
> >   use Set_integer8_mod
> >   use Set_integer8_extensions_mod
> >   use Set_real8_mod
> > 
> >   use, intrinsic :: ISO_C_Binding, only : f64 => C_DOUBLE , i64 => &
> >         C_INT64_T
> >   use, intrinsic :: ISO_FORTRAN_ENV, only : stdout => output_unit
> > 
> >   implicit none
> > 
> >   write(stdout, '(I0)', advance="yes") update_multiple()
> >   write(stdout, '(I0)', advance="yes") set_union()
> > 
> > end program prog_prog_boo
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can we avoid printing
> > ```fortran
> >   use Set_integer8_mod
> >   use Set_integer8_extensions_mod
> >   use Set_real8_mod
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > since we already use them in `boo`?
> 
> I'm not sure that this is really related to this PR.
> 
> I agree that these imports are superfluous but they are a little tricky to avoid. We need to print all imports that are pertinent to the scope. If we do `use boo` we only get the public methods from `boo` so we shouldn't get access to anything imported inside the `boo` module. This is why all pertinent imports included by `boo` need repeating in the program. If the program scope was completely separate from the module scope then the number of imports used here could be reduced but in Python the program scope is a child of the module scope so the program should have access to all the objects imported in the module.

Thank you for the clarification!

2025-01-08 15:33 UTC, jalalium approved these changes
Well done!

2025-01-08 15:40 UTC, EmilyBourne commented
/bot run pr_tests

2025-01-08 16:08 UTC, merged