Use iso_c types for fortran to ensure compatibility for the cwrapper
pyccel/pyccel pull request #525
Opened 2020-11-04 13:15 UTC by mostafaMamoni

- [ ] Use iso_c_binding to specify precision

- [ ] Mark all structures and functions in the f2py_X.F90 file with bind (c)

2020-11-04 13:24 UTC, EmilyBourne requested changes
This looks good to me but it seems to be failing for almost every test on travis. Are you sure f2py knows how to handle iso_c_binding?

2020-11-04 13:24 UTC, EmilyBourne commented on pyccel/codegen/printing/fcode.py
> +        imports += 'use ISO_C_BINDING'
This should end with a `\n`

2020-11-04 13:24 UTC, EmilyBourne commented on pyccel/codegen/printing/fcode.py
> +        imports += 'use ISO_C_BINDING'
This should end with a `\n`

2020-11-04 22:27 UTC, yguclu commented
> This looks good to me but it seems to be failing for almost every test on travis. Are you sure f2py knows how to handle iso_c_binding?

I agree, most likely there is a problem with f2py. @mostafaMamoni Do the tests run on your machine?

2020-11-04 22:34 UTC, yguclu commented
If indeed f2py does not understand the `use iso_c_binding` instruction, that would mean that this PR and #527 need each other to work. Hence I suggest that we merge this branch into [`ebourne_remove_f2py`](https://github.com/pyccel/pyccel/tree/ebourne_remove_f2py).

2020-11-06 17:39 UTC, EmilyBourne commented
This branch is now merged into PR #527 as the 2 are inter-dependant

2020-11-06 17:39 UTC, closed without merging