Correct Dlist so it works with any ordering
pyccel/pyccel pull request #612
Opened 2020-12-19 08:13 UTC by EmilyBourne

The following example is incorrectly translated:
```
x = [3,5,7]
y = 2*x
```
but:
```
x = [3,5,7]
y = x*2
```
works. Fix `_visit_PyccelMul` call to `_visit_Dlist` to work for both orderings. Fixes #610

2020-12-19 09:14 UTC, nhamidn requested changes

2020-12-19 09:14 UTC, nhamidn commented on pyccel/parser/semantic.py
> +        print([type(a) for a in args])
a print needs to be removed

2020-12-19 09:17 UTC, EmilyBourne commented on pyccel/parser/semantic.py
> +        print([type(a) for a in args])
oops

2020-12-19 13:25 UTC, saidctb approved these changes

2020-12-21 14:19 UTC, yguclu approved these changes

2020-12-21 15:03 UTC, merged