exempt augassign from raising reassigning errors
pyccel/pyccel pull request #638
Opened 2020-12-24 14:14 UTC by saniQQ

exempt the augassign from raising reassigning errors for it will not reallocate the arrays.

2020-12-24 14:16 UTC, EmilyBourne approved these changes

2020-12-24 14:17 UTC, EmilyBourne requested changes
Could you add a test please. One should be enough :+1:

2020-12-24 14:42 UTC, saniQQ commented
> Could you add a test please. One should be enough 👍

i added the tests in the Codegen tests is it enough?
i added them there because C still can't handle the augassign.

2020-12-24 15:40 UTC, EmilyBourne commented
> > Could you add a test please. One should be enough +1
> 
> i added the tests in the Codegen tests is it enough?
> i added them there because C still can't handle the augassign.

I always prefer an end-to-end test. Fortran can handle the augassign and this problem is in the semantic stage so it shouldn't matter which language it's tested with

2020-12-25 08:42 UTC, MenoIy approved these changes

2020-12-26 18:18 UTC, EmilyBourne approved these changes

2020-12-28 18:08 UTC, yguclu approved these changes

2020-12-29 16:09 UTC, merged