Handle int8 int16 bool
pyccel/pyccel pull request #776
Opened 2021-03-01 15:43 UTC by abkhaoula

Fixed the miss handling of the int8 int16 and bool types of the numpy lib

2021-03-01 15:58 UTC, mostafaMamoni requested changes

2021-03-01 15:58 UTC, mostafaMamoni commented on pyccel/ast/datatypes.py
> +                                 'bool' :('bool',1),
we are already setting `bool` precision [here](https://github.com/pyccel/pyccel/pull/776/files#diff-62efbcaf36568e28d52d7aa8d3d25d515157238dd4bff069483b0e8778cf9a9eR111)

2021-03-01 15:58 UTC, mostafaMamoni commented on pyccel/ast/numpyext.py
> +        4 : NumpyBool}
can you please keep one casting function here, since they are almost the same and have the same precision?

2021-03-01 15:58 UTC, mostafaMamoni commented on pyccel/ast/numpyext.py
> +    'bool'   : NumpyBool,
can you align this line please ^^ ?.

2021-03-01 20:41 UTC, mostafaMamoni approved these changes
All good for me, just you need to deal with the empty files without removing them.

2021-03-02 07:26 UTC, EmilyBourne requested changes
Looks good :+1:
Could you please add some small tests to ensure that these casting functions work as expected for all different types.
E.g:
```
np.int8(True)
np.int8(1022)
```
etc

2021-03-02 15:36 UTC, EmilyBourne approved these changes

2021-03-03 16:21 UTC, yguclu requested changes
Good job @abkhaoula!

I'd like you to fix the formatting in a couple of places.

2021-03-03 16:21 UTC, yguclu commented on pyccel/ast/numpyext.py
> +    'int16': NumpyInt16,
If you don't mind, could you please align the `:` signs to all the others above and below?

2021-03-03 16:21 UTC, yguclu commented on pyccel/ast/numpyext.py
> +        return super().__new__(cls, arg)
Can you please add an empty line after this class definition?

This way we match the same formatting as the rest of the file.

2021-03-03 16:23 UTC, yguclu requested changes

2021-03-03 16:23 UTC, yguclu commented on pyccel/ast/numpyext.py
> +        2: NumpyInt16,
Here too, can you please align the `:` signs to the ones below?

2021-03-03 17:42 UTC, yguclu approved these changes

2021-03-03 21:48 UTC, merged