Treat extra spaces in flag options
pyccel/pyccel pull request #884
Opened 2021-04-29 12:12 UTC by EmilyBourne

Handle extra spaces in the `fflags` argument passed to `execute_pyccel`. Fixes #881. Add an unnecessary space to a function using `fflags` to act as a test

2021-04-29 17:39 UTC, saidctb approved these changes

2021-04-30 07:08 UTC, yguclu requested changes

2021-04-30 07:08 UTC, yguclu commented on pyccel/codegen/pipeline.py
> +        fflags = [f for f in fflags.strip().split(' ') if f]
Isn't it sufficient to use `split` without any argument? That is
```python
fflags = fflags.split()
```
According to the [documentation](https://docs.python.org/3/library/stdtypes.html#str.split)
> If sep is not specified or is None, a different splitting algorithm is applied: runs of consecutive whitespace are regarded as a single separator, and the result will contain no empty strings at the start or end if the string has leading or trailing whitespace

2021-04-30 07:50 UTC, yguclu approved these changes

2021-04-30 07:51 UTC, yguclu commented on pyccel/codegen/pipeline.py
> +        fflags = [f for f in fflags.strip().split(' ') if f]
Done in cd131e5

2021-04-30 07:52 UTC, merged